# -*- coding: utf-8 -*-
"""fig3_splitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k6JQ2XVNN-nxX1rV_nVCxoUcYvYMzKwc
"""

# -*- coding: utf-8 -*-
"""
fig3_splitting.py

Evaluates the fractional-power branching of the eigenvalues, confirming
the non-analytic square-root splitting near generic EP2s and the
cubic-root scaling at the cusp.
"""

import numpy as np
import matplotlib.pyplot as plt
import os

# --- STYLE CONFIGURATION ---
plt.rcParams.update({
    "text.usetex": False,
    "mathtext.fontset": "dejavuserif",
    "font.family": "serif",
    "axes.labelsize": 14,
    "font.size": 12,
    "legend.fontsize": 12,
    "xtick.labelsize": 12,
    "ytick.labelsize": 12
})

def cubic_polynomial_roots(De, Lambda):
    """Finds the roots of: -i*De*w^3 + w^2 + i*(De-Lambda)*w - 1 = 0"""
    coeffs = [-1j * De, 1.0, 1j * (De - Lambda), -1.0]
    return np.roots(coeffs)

def main():
    os.makedirs('figures', exist_ok=True)
    print("Generating Figure 3 (Numerical Splitting)...")

    # Base Cusp parameters
    De_star, Lambda_star = 0.0, 2.0

    # Base Generic EP2 parameters (e.g., y=2)
    y_ep2 = 2.0
    De_ep2 = (y_ep2**2 - 1) / (2 * y_ep2**3)
    Lambda_ep2 = (y_ep2**2 + 1)**2 / (2 * y_ep2**3)

    epsilons = np.logspace(-6, -2, 50)
    splitting_ep2 = []
    splitting_cusp = []

    for eps in epsilons:
        # --- Transverse perturbation at Generic EP2 ---
        roots_ep2 = cubic_polynomial_roots(De_ep2, Lambda_ep2 + eps)
        # Minimum distance identifies the two coalescing roots robustly
        diffs_ep2 = [np.abs(roots_ep2[0]-roots_ep2[1]),
                     np.abs(roots_ep2[1]-roots_ep2[2]),
                     np.abs(roots_ep2[0]-roots_ep2[2])]
        splitting_ep2.append(min(diffs_ep2))

        # --- Transverse perturbation at Cusp ---
        roots_cusp = cubic_polynomial_roots(De_star + eps, Lambda_star)
        # Maximum distance measures the spread of the 3-sheet coalescence
        diff_cusp = max([np.abs(roots_cusp[0]-roots_cusp[1]),
                         np.abs(roots_cusp[1]-roots_cusp[2]),
                         np.abs(roots_cusp[0]-roots_cusp[2])])
        splitting_cusp.append(diff_cusp)

    fig, ax = plt.subplots(figsize=(7, 5))

    # Plot data
    ax.loglog(epsilons, splitting_ep2, 'bo', label='Generic EP2 Numerical Data', markersize=5, alpha=0.7)
    ax.loglog(epsilons, splitting_cusp, 'ro', label='Cusp Numerical Data', markersize=5, alpha=0.7)

    # Plot theoretical slopes
    anchor_ep2 = splitting_ep2[-1] / (epsilons[-1]**0.5)
    anchor_cusp = splitting_cusp[-1] / (epsilons[-1]**0.333)

    ax.loglog(epsilons, anchor_ep2 * epsilons**0.5, 'b--', label=r'$\delta \sim |\epsilon|^{1/2}$ (Theory)')
    ax.loglog(epsilons, anchor_cusp * epsilons**0.333, 'r--', label=r'$\delta \sim |\epsilon|^{1/3}$ (Theory)')

    ax.set_xlabel(r'Transverse perturbation magnitude $|\epsilon|$')
    ax.set_ylabel(r'Eigenvalue splitting $|\delta|$')
    ax.set_title('Eigenvalue Splitting near Degeneracies')
    ax.grid(True, which="both", ls="--", alpha=0.4)
    ax.legend()

    save_path = os.path.join('figures', 'fig3_splitting.pdf')
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()

    print(f"Saved: {save_path}")

if __name__ == "__main__":
    main()