# -*- coding: utf-8 -*-
"""script 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/158e_m43ja7uZ8_cfPM-bMhySL-yygnNq
"""

# -*- coding: utf-8 -*-
"""
fig4_physical_NS_application.py

Simulates the QNM phenomenological crossing for a hypermassive
post-merger neutron star remnant traversing the EP2 curve.
"""

import numpy as np
import matplotlib.pyplot as plt
import os
import itertools
from scipy.optimize import fsolve

# --- STYLE CONFIGURATION ---
plt.rcParams.update({
    "text.usetex": False,
    "mathtext.fontset": "dejavuserif",
    "font.family": "serif",
    "axes.labelsize": 12,
    "font.size": 11,
    "legend.fontsize": 9,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10
})

# --- ASTROPHYSICAL PARAMETERS: BNS Post-Merger Remnant ---
M_solar = 1.989e33
M = 2.7 * M_solar
R = 15e5
rho = M / ((4.0/3.0) * np.pi * R**3)
f_0 = 3500.0
omega_0 = 2 * np.pi * f_0

zeta_scale = rho * R**2 * omega_0
tau_scale = 1.0 / omega_0

def get_qnm_frequencies(tau_sec, zeta_cgs):
    De = tau_sec / tau_scale
    Lambda = zeta_cgs / zeta_scale
    coeffs = [-1j * De, 1.0, 1j * (De - Lambda), -1.0]
    return np.roots(coeffs) * f_0

def main():
    os.makedirs('figures', exist_ok=True)

    # Hot matter relaxation time (~5 MeV)
    tau_target_ms = 0.005
    tau_sec = tau_target_ms * 1e-3
    De_fixed = tau_sec / tau_scale

    # --- EXACT ANALYTICAL ROOTS (Double EP2 Crossing) ---
    def equation_y(y):
        return (y**2 - 1) / (2 * y**3) - De_fixed

    y_crit_1 = fsolve(equation_y, 1.2)[0]
    Lambda_crit_1 = (y_crit_1**2 + 1)**2 / (2 * y_crit_1**3)
    zeta_crit_1 = Lambda_crit_1 * zeta_scale

    y_crit_2 = fsolve(equation_y, 4.0)[0]
    Lambda_crit_2 = (y_crit_2**2 + 1)**2 / (2 * y_crit_2**3)
    zeta_crit_2 = Lambda_crit_2 * zeta_scale

    # --- ROOT TRACKING ---
    Lambda_array = np.linspace(0.8, 2.5, 1000)
    zeta_array = Lambda_array * zeta_scale

    roots_list = []
    prev_roots = get_qnm_frequencies(tau_sec, zeta_array[0])
    prev_roots = sorted(prev_roots, key=lambda x: -x.real)
    roots_list.append(prev_roots)

    for z in zeta_array[1:]:
        current_roots = get_qnm_frequencies(tau_sec, z)
        best_perm = min(itertools.permutations(current_roots),
                        key=lambda p: sum(abs(p[i] - roots_list[-1][i]) for i in range(3)))
        roots_list.append(best_perm)

    roots_list = np.array(roots_list)

    # --- PLOTTING ---
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5.5))

    zeta_plot = zeta_array / 1e31
    z_c1 = zeta_crit_1 / 1e31
    z_c2 = zeta_crit_2 / 1e31

    def add_lambda_axis(ax):
        ax2_top = ax.twiny()
        ax2_top.set_xlim(ax.get_xlim())
        ticks_zeta = ax.get_xticks()
        ticks_lambda = (ticks_zeta * 1e31) / zeta_scale
        ax2_top.set_xticks(ticks_zeta)
        ax2_top.set_xticklabels([f"{l:.2f}" for l in ticks_lambda])
        ax2_top.set_xlabel(r'Dimensionless Viscous Coupling $\Lambda$')
        return ax2_top

    # Panel 1: Oscillation
    ax1.plot(zeta_plot, [r[0].real for r in roots_list], color='blue', linewidth=2, label='Propagating Mode (+)')
    ax1.plot(zeta_plot, [r[2].real for r in roots_list], color='cyan', linewidth=2, linestyle='--', label='Propagating Mode (-)')
    ax1.plot(zeta_plot, [r[1].real for r in roots_list], color='gray', linestyle=':', linewidth=2, label='Relaxation Mode')

    ax1.axvline(x=z_c1, color='red', linestyle=':', alpha=0.8, label='EP2: Overdamping')
    ax1.axvline(x=z_c2, color='purple', linestyle=':', alpha=0.8, label='EP2: Relaxation Collision')

    ax1.set_xlabel(r'Bulk Viscosity $\zeta$ ($10^{31}$ g cm$^{-1}$ s$^{-1}$)')
    ax1.set_ylabel(r'Mode Frequency $\mathrm{Re}(f)$ (Hz)')
    ax1.set_title(r'Overdamping of Oscillations')
    ax1.grid(True, linestyle='--', alpha=0.5)
    ax1.legend(loc='best')
    add_lambda_axis(ax1)

    # Panel 2: Damping
    ax2.plot(zeta_plot, [-r[0].imag for r in roots_list], color='orange', linewidth=2, label='Fluid Branch 1 (+)')
    ax2.plot(zeta_plot, [-r[2].imag for r in roots_list], color='green', linewidth=2, linestyle='--', label='Fluid Branch 2 (-)')
    ax2.plot(zeta_plot, [-r[1].imag for r in roots_list], color='purple', linewidth=2, label='Relaxation Branch')

    ax2.axvline(x=z_c1, color='red', linestyle=':', alpha=0.8, label='EP2: Overdamping')
    ax2.axvline(x=z_c2, color='purple', linestyle=':', alpha=0.8, label='EP2: Relaxation Collision')

    ax2.set_xlabel(r'Bulk Viscosity $\zeta$ ($10^{31}$ g cm$^{-1}$ s$^{-1}$)')
    ax2.set_ylabel(r'Decay Rate $-\mathrm{Im}(f)$ (Hz)')
    ax2.set_title(r'EP2 Degeneracy in the Damping Spectrum')
    ax2.grid(True, linestyle='--', alpha=0.5)
    ax2.legend(loc='best')
    add_lambda_axis(ax2)

    plt.suptitle(fr'Post-Merger Remnant QNM Evolution across EP2 ($\tau = {tau_target_ms}$ ms, $M=2.7 M_\odot$, $f_0=3.5$ kHz)', fontsize=14, y=1.05)
    plt.tight_layout()

    save_path = os.path.join('figures', 'fig4_physical_NS_application.pdf')
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()

    print(f"Analytical EP2 1: zeta = {z_c1:.4f}e31 (Lambda = {Lambda_crit_1:.3f})")
    print(f"Analytical EP2 2: zeta = {z_c2:.4f}e31 (Lambda = {Lambda_crit_2:.3f})")

if __name__ == "__main__":
    main()