(* ============================================================================
   *** SUPERSEDED -- DO NOT USE FOR THE PUBLISHED FIGURE 5 ***

   This file computes C_proj with the identification k_eff ~ 1/R (L = R) and
   f0 = 3.5 kHz.  Section 9.5 of the manuscript now rejects that identification
   explicitly: for a fundamental compressive mode with a node at the stellar
   surface, k_eff = pi/R, and L = R gives c_s = omega0 R ~ 1.1 c, which is
   acausal.  The couplings quoted below (Lambda* = 1.712, 2.357) belong to the
   earlier, acausal fiducial point.

   The published figure 5 uses the causal construction of section 9.5:
       f0 = 3.0 kHz,  L = R/pi,  De = 0.17,  gamma_GW = 0.03,
       C_proj = 1/(rho_bar L^2 omega0) = 6.12629e-31 g^-1 cm s,
       EP2 couplings Lambda* = 1.565195 and 1.633207,
       A3 cusp Lambda* = 1.487038,
       zeta ~ 2.55 and 2.67 x 10^30 g cm^-1 s^-1,
   and is generated by code/make_fig5_postmerger.py, which is self-contained.

   This file is retained only so that the provenance of the earlier figure is
   auditable.  Set CAUSAL = True below to evaluate the current construction.
   ============================================================================ *)

CAUSAL = False;   (* True -> k_eff = pi/R, f0 = 3.0 kHz (published) *)

(* ::Package:: *)

(* =============================================================================
   projection_coefficient.wl
   -----------------------------------------------------------------------------
   Derivation of the physical projection coefficient C_proj that maps the
   physical bulk viscosity zeta (g cm^-1 s^-1) to the dimensionless viscous
   coupling Lambda of the open cubic normal form of CQG-115250:

       Lambda = zeta / (rho * L^2 * omega0)  ==>  C_proj = 1/(rho * L^2 * omega0)

   The coefficient is fixed entirely by the fiducial post-merger star already
   declared in the manuscript (M = 2.7 M_sun, R = 15 km thermally-inflated
   radius, fundamental compressive frequency f0 = 3.5 kHz; cf. Radice 2022).
   No equation-of-state input beyond (M, R) is required:

     * rho   : mean density, rho_bar = 3 M / (4 pi R^3)
     * L      : macroscopic mode length, L = R  (the fundamental compressive
                mode has no radial nodes, k_eff ~ 1/R)
     * omega0 : angular frequency of the fundamental mode, omega0 = 2 pi f0,
                with f0 the value quoted in the manuscript.

   This script is self-contained and reproducible; it prints every intermediate
   quantity and then maps the two exact sector-0 EP2 couplings to their
   physical viscosities.
   ============================================================================= *)

(* ---- physical constants (CGS) ---- *)
GG   = 6.674*10^-8;     (* cm^3 g^-1 s^-2 *)
cc   = 3.0*10^10;       (* cm/s *)
Msun = 1.989*10^33;     (* g *)

(* ---- fiducial star (as declared in the manuscript) ---- *)
Mstar = 2.7*Msun;      (* g   *)
Rkm   = 15;            (* km  -- thermally inflated post-merger radius *)
Rstar = Rkm*10^5;      (* cm  *)
f0kHz = If[CAUSAL, 3.0, 3.5];   (* kHz -- fundamental compressive mode *)

(* ---- (1) mean density ---- *)
rhoBar = 3*Mstar/(4*Pi*Rstar^3);
Print["Mean density   rho_bar = 3M/(4 pi R^3) = ",
      ScientificForm[N[rhoBar], 5], " g/cm^3"];

(* ---- (2) macroscopic mode length ---- *)
Lscale = If[CAUSAL, Rstar/Pi, Rstar];
(* causal: node at the surface, k_eff = pi/R => L = R/pi.
   legacy (CAUSAL=False): k_eff ~ 1/R => L = R.  See section 9.5. *)
Print["Mode length    L = R = ", ScientificForm[N[Lscale], 5], " cm (",
      N[Rkm], " km)"];

(* ---- (3) fundamental angular frequency ---- *)
omega0 = 2*Pi*f0kHz*10^3;   (* rad/s *)
Print["Angular freq   omega0 = 2 pi f0 = ", ScientificForm[N[omega0], 5],
      " rad/s  (f0 = ", N[f0kHz], " kHz)"];

(* ---- projection coefficient ---- *)
Cproj = 1/(rhoBar*Lscale^2*omega0);
Print["-----------------------------------------------------------"];
Print["PROJECTION COEFFICIENT  C_proj = 1/(rho L^2 omega0) = ",
      ScientificForm[N[Cproj], 5], " g^-1 cm s"];
Print["Compactness    GM/(R c^2) = ", N[GG*Mstar/(Rstar*cc^2), 4]];
Print["-----------------------------------------------------------"];

(* ---- map the two exact sector-0 EP2 couplings to physical viscosity ----
   Lambda* are the exact EP2 coalescences of the open cubic at De = 0.11,
   gamma = 0.03 (see cqg_core.py / certify_table1.py).                    *)
Lam1 = If[CAUSAL, 1.565195, 1.712359];
Lam2 = If[CAUSAL, 1.633207, 2.357256];
Print["Sector-0 EP2 #1:  Lambda* = ", Lam1,
      "  ->  zeta = ", ScientificForm[N[Lam1/Cproj], 4], " g cm^-1 s^-1"];
Print["Sector-0 EP2 #2:  Lambda* = ", Lam2,
      "  ->  zeta = ", ScientificForm[N[Lam2/Cproj], 4], " g cm^-1 s^-1"];

(* ---- emit the (zeta, Lambda) grid used for the fig. 6 sweep ---- *)
zetaGrid = Table[z, {z, 1.5*10^31, 5.5*10^31, (5.5-1.5)*10^31/400}];
Export["projection_grid.csv",
       Prepend[Transpose[{zetaGrid, Cproj*zetaGrid}], {"zeta_cgs","Lambda"}]];
Print["Wrote projection_grid.csv (", Length[zetaGrid], " rows)."];
