# -*- coding: utf-8 -*-
"""fig1_ep_curve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13a7Ko2i5ZTvijLFlrsjz68Qao7ZPK9ZG
"""

# -*- coding: utf-8 -*-
"""
fig1_ep_curve.py

Solves the cubic discriminant locus to extract the global
exceptional-point (EP2) curve in the (De, Lambda) parameter plane.
"""

import numpy as np
import matplotlib.pyplot as plt
import os

# --- STYLE CONFIGURATION ---
plt.rcParams.update({
    "text.usetex": False,
    "mathtext.fontset": "dejavuserif",
    "font.family": "serif",
    "axes.labelsize": 14,
    "font.size": 12,
    "legend.fontsize": 12,
    "xtick.labelsize": 12,
    "ytick.labelsize": 12
})

def calculate_ep_curve(y_min=1.0, y_max=5.0, num_points=1000):
    """Calculates the parametric EP2 curve."""
    y = np.linspace(y_min, y_max, num_points)
    De = (y**2 - 1) / (2 * y**3)
    Lambda = (y**2 + 1)**2 / (2 * y**3)
    return De, Lambda

def main():
    os.makedirs('figures', exist_ok=True)
    print("Generating Figure 1 (EP2 Curve)...")

    De_vals, Lambda_vals = calculate_ep_curve(y_min=1.0, y_max=4.0)
    De_star, Lambda_star = 0.0, 2.0

    fig, ax = plt.subplots(figsize=(7, 5))
    ax.plot(De_vals, Lambda_vals, color='black', linewidth=1.5, label=r'Discriminant locus $\Delta=0$')
    ax.plot(De_star, Lambda_star, marker='o', markersize=6, color='red', label=r'Cusp $(De_*, \Lambda_*) = (0, 2)$')

    ax.set_xlabel(r'Deborah number $De$')
    ax.set_ylabel(r'Viscous coupling $\Lambda$')
    ax.set_title(r'Exceptional-Point Curve in the $(De, \Lambda)$ Plane')
    ax.grid(True, linestyle='--', alpha=0.6)
    ax.legend(loc='upper right')
    ax.set_xlim(-0.02, max(De_vals) * 1.1)
    ax.set_ylim(1.8, max(Lambda_vals) * 1.05)

    save_path = os.path.join('figures', 'fig1_ep_curve.pdf')
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()

    print(f"Saved: {save_path}")

if __name__ == "__main__":
    main()
