# -*- coding: utf-8 -*-
"""fig2_cusp_zoom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6n5GQknM9z2yF6uTNsqfxtzM1U5rUR3
"""

# -*- coding: utf-8 -*-
"""
fig2_cusp_zoom.py

Generates the local geometric structure of the A_3 cusp singularity
at the Navier-Stokes boundary (De = 0) for the cubic normal form.
"""

import numpy as np
import matplotlib.pyplot as plt
import os

# --- STYLE CONFIGURATION ---
plt.rcParams.update({
    "text.usetex": False,
    "mathtext.fontset": "dejavuserif",
    "font.family": "serif",
    "axes.labelsize": 14,
    "font.size": 12,
    "legend.fontsize": 12,
    "xtick.labelsize": 12,
    "ytick.labelsize": 12
})

def calculate_ep_curve(y_array):
    """Calculates the De and Lambda values given an array of y (imaginary frequency)."""
    De = (y_array**2 - 1) / (2 * y_array**3)
    Lambda = (y_array**2 + 1)**2 / (2 * y_array**3)
    return De, Lambda

def main():
    os.makedirs('figures', exist_ok=True)
    print("Generating Figure 2 (Cusp Zoom)...")

    # --- CUSP PARAMETERS ---
    # The cusp occurs exactly at y = 1.0
    De_star, Lambda_star = 0.0, 2.0

    # --- PHYSICAL BRANCH (De > 0) ---
    # Occurs when y > 1.0
    y_phys = np.linspace(1.0, 2.0, 500)
    De_phys, Lambda_phys = calculate_ep_curve(y_phys)

    # --- MATHEMATICAL CONTINUATION (De < 0) ---
    # Occurs when 0 < y < 1.0
    y_math = np.linspace(0.4, 1.0, 500)
    De_math, Lambda_math = calculate_ep_curve(y_math)

    # --- PLOTTING ---
    fig, ax = plt.subplots(figsize=(7, 5))

    # Plot mathematical continuation (dashed gray)
    ax.plot(De_math, Lambda_math, color='gray', linestyle='--', linewidth=1.5,
            label=r'Math. continuation ($De < 0$)')

    # Plot physical EP2 branch (solid black)
    ax.plot(De_phys, Lambda_phys, color='black', linewidth=1.5,
            label=r'Physical EP2 branch ($De > 0$)')

    # Plot Cusp Singularity (red dot)
    ax.plot(De_star, Lambda_star, marker='o', markersize=7, color='red',
            label=r'Cusp Singularity $A_3$')

    # Plot Navier-Stokes boundary (dotted line at De = 0)
    ax.axvline(x=0, color='navy', linestyle=':', alpha=0.5,
               label=r'Navier-Stokes limit ($De = 0$)')

    # Formatting and limits to match the paper
    ax.set_xlabel(r'Deborah number $De$')
    ax.set_ylabel(r'Viscous coupling $\Lambda$')
    ax.set_title(r'Local Geometry of the $A_3$ Cusp Singularity')
    ax.grid(True, linestyle='--', alpha=0.4)

    ax.set_xlim(-0.4, 0.4)
    ax.set_ylim(1.8, 3.5)

    ax.legend(loc='upper right')

    # Save
    plt.tight_layout()
    save_path = os.path.join('figures', 'fig2_cusp_zoom.pdf')
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()

    print(f"Figure 2 generated successfully and saved to {save_path}.")

if __name__ == "__main__":
    main()